"""Translate a baseline audio evidence packet into O/M/E candidate fields.

This is the first minimal mechanism-to-OME adapter for MSSL.
It reads `audio_evidence_packet.json` generated by
`scripts/run_librosa_baseline_evidence.py` and writes:

- ome_mapping_packet.json

The output is not a listening report and does not create confirmed auditory
objects. It only creates auditable O-space, M-domain, E-space, and object-input
candidates with explicit support and over-interpretation boundaries.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


DEFAULT_OUTPUT_NAME = "ome_mapping_packet.json"
EPSILON = 1e-12


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Translate baseline audio evidence into minimal O/M/E candidates."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to audio_evidence_packet.json generated by the librosa baseline adapter.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional output path. Default: write ome_mapping_packet.json next to input.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f"Evidence packet not found: {input_path}")

    evidence_packet = json.loads(input_path.read_text(encoding="utf-8"))
    mapping_packet = build_mapping_packet(evidence_packet, input_path)

    output_path = Path(args.output) if args.output else input_path.with_name(DEFAULT_OUTPUT_NAME)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(mapping_packet, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {output_path}")


def build_mapping_packet(evidence_packet: dict[str, Any], input_path: Path) -> dict[str, Any]:
    features = evidence_packet.get("features", {})
    temporal = features.get("temporal_evidence", {})
    spectral = features.get("spectral_evidence", {})
    rhythm = features.get("rhythm_evidence", {})
    harmonic = features.get("harmonic_evidence", {})
    mel_mfcc = features.get("mel_mfcc_evidence", {})
    stereo = features.get("stereo_proxy_evidence", {})

    o_space = [
        spectral_brightness_candidate(spectral),
        spectral_density_candidate(spectral),
        harmonic_contour_candidate(harmonic),
        timbre_shape_candidate(mel_mfcc),
    ]

    m_domain = [
        pressure_transfer_candidate(temporal),
        activity_continuity_candidate(temporal),
        pulse_transfer_candidate(rhythm),
    ]

    e_space = [
        perceived_pressure_candidate(temporal),
        receiver_width_candidate(stereo),
        receiver_balance_candidate(stereo),
        receiver_spread_candidate(stereo),
        upper_tendency_candidate(spectral),
    ]

    object_inputs = [
        rhythmic_object_input(rhythm),
        transient_activity_input(rhythm, temporal),
        harmonic_layer_input(harmonic),
        texture_mass_input(spectral, mel_mfcc),
    ]

    mapping_packet = {
        "schema": "mssl_mechanism_to_ome_mapping_v0_1",
        "mapper": {
            "name": "mechanism_to_ome_baseline",
            "role": "minimal baseline mapper",
            "status": "candidate mapping only; not auditory object tracking and not listening report",
        },
        "input_packet": {
            "path": str(input_path),
            "schema": evidence_packet.get("schema"),
            "adapter": evidence_packet.get("adapter", {}).get("name"),
            "filename": evidence_packet.get("input", {}).get("filename"),
            "sample_rate": evidence_packet.get("input", {}).get("sample_rate"),
            "analyzed_duration_seconds": evidence_packet.get("input", {}).get("analyzed_duration_seconds"),
        },
        "policy": {
            "not_a_listening_report": True,
            "not_confirmed_object_identity": True,
            "not_physical_source_localization": True,
            "not_genre_or_taste_judgment": True,
            "next_required_step": "object candidate building and temporal-spatial object tracking",
        },
        "ome_candidates": {
            "O_space": o_space,
            "M_domain": m_domain,
            "E_space": e_space,
            "object_candidate_inputs": object_inputs,
        },
        "mapping_rule_index": mapping_rule_index(),
        "audit": {
            "feature_warnings_from_input": evidence_packet.get("feature_warnings", []),
            "global_cannot_prove": [
                "cannot prove whether the song is good",
                "cannot prove genre, emotion, cultural meaning, or review language",
                "cannot prove real physical source location from stereo proxy fields",
                "cannot identify singer, speaker, lyric, or instrument identity",
                "cannot replace human annotation or calibration",
            ],
        },
    }
    return sanitize(mapping_packet)


def spectral_brightness_candidate(spectral: dict[str, Any]) -> dict[str, Any]:
    centroid = stat_mean(spectral, "spectral_centroid_hz")
    rolloff = stat_mean(spectral, "spectral_rolloff_hz")
    score = bounded_score(relative_value(centroid, low=800.0, high=5000.0), relative_value(rolloff, low=2000.0, high=12000.0))
    return candidate(
        field="source_side_spectral_brightness_candidate",
        layer="O-space",
        value=score,
        confidence=confidence_from_values(centroid, rolloff),
        can_support=[
            "modeled source-side upper-frequency energy tendency",
            "brightness or upper-band presence as audio evidence",
        ],
        cannot_prove=[
            "cannot prove instrument identity",
            "cannot prove real source location",
            "cannot directly become report language such as bright, cold, sharp, or beautiful",
        ],
        source_features=["spectral_centroid_hz.mean", "spectral_rolloff_hz.mean"],
    )


def spectral_density_candidate(spectral: dict[str, Any]) -> dict[str, Any]:
    bandwidth = stat_mean(spectral, "spectral_bandwidth_hz")
    flatness = stat_mean(spectral, "spectral_flatness")
    score = bounded_score(relative_value(bandwidth, low=500.0, high=6000.0), relative_value(flatness, low=0.02, high=0.45))
    return candidate(
        field="source_side_spectral_density_candidate",
        layer="O-space",
        value=score,
        confidence=confidence_from_values(bandwidth, flatness),
        can_support=[
            "broad-band or noisy spectral mass candidate",
            "texture-density evidence before object identification",
        ],
        cannot_prove=[
            "cannot prove noise wall, guitar, synth, voice, or distortion identity",
            "cannot prove emotional density",
        ],
        source_features=["spectral_bandwidth_hz.mean", "spectral_flatness.mean"],
    )


def harmonic_contour_candidate(harmonic: dict[str, Any]) -> dict[str, Any]:
    strength = as_float(harmonic.get("dominant_pitch_class_strength"))
    pitch_class = harmonic.get("dominant_pitch_class_candidate")
    return candidate(
        field="source_side_harmonic_contour_candidate",
        layer="O-space",
        value=bounded_score(strength),
        confidence=confidence_from_values(strength),
        can_support=[
            "pitch-class concentration candidate",
            "harmonic persistence input for later object tracking",
        ],
        cannot_prove=[
            "cannot prove musical key",
            "cannot prove melody truth",
            "cannot prove song meaning",
        ],
        source_features=["dominant_pitch_class_candidate", "dominant_pitch_class_strength"],
        extra={"dominant_pitch_class_candidate": pitch_class},
    )


def timbre_shape_candidate(mel_mfcc: dict[str, Any]) -> dict[str, Any]:
    mfcc_stats = mel_mfcc.get("mfcc_stats", [])
    mfcc0 = list_stat_mean(mfcc_stats, 0)
    mfcc1 = list_stat_mean(mfcc_stats, 1)
    score = bounded_score(relative_value(abs_or_none(mfcc0), low=10.0, high=300.0), relative_value(abs_or_none(mfcc1), low=5.0, high=120.0))
    return candidate(
        field="source_side_timbre_shape_candidate",
        layer="O-space",
        value=score,
        confidence=confidence_from_values(mfcc0, mfcc1),
        can_support=[
            "coarse timbre-envelope change as object evidence",
            "texture-shape input for later comparison across windows",
        ],
        cannot_prove=[
            "cannot prove singer or speaker identity",
            "cannot prove instrument identity",
            "cannot prove mood or style",
        ],
        source_features=["mfcc_stats[0].mean", "mfcc_stats[1].mean"],
    )


def pressure_transfer_candidate(temporal: dict[str, Any]) -> dict[str, Any]:
    rms_mean = stat_mean(temporal, "rms")
    rms_max = stat_value(temporal, "rms", "max")
    score = bounded_score(relative_value(rms_mean, low=0.01, high=0.25), relative_value(rms_max, low=0.03, high=0.7))
    return candidate(
        field="pressure_transfer_candidate",
        layer="M-domain",
        value=score,
        confidence=confidence_from_values(rms_mean, rms_max),
        can_support=[
            "energy transfer magnitude candidate across the analyzed window",
            "input to perceived pressure and foreground activity mapping",
        ],
        cannot_prove=[
            "cannot prove physical distance",
            "cannot prove loudness perception without calibration",
        ],
        source_features=["rms.mean", "rms.max"],
    )


def activity_continuity_candidate(temporal: dict[str, Any]) -> dict[str, Any]:
    rms_delta_std = stat_value(temporal, "rms_delta", "std")
    rms_mean = stat_mean(temporal, "rms")
    # High mean with lower delta suggests steadier continuity; large delta suggests broken/transient behavior.
    continuity = clamp01(relative_value(rms_mean, low=0.01, high=0.25) * (1.0 - relative_value(rms_delta_std, low=0.005, high=0.12)))
    return candidate(
        field="activity_continuity_candidate",
        layer="M-domain",
        value=continuity,
        confidence=confidence_from_values(rms_delta_std, rms_mean),
        can_support=[
            "sustained activity candidate",
            "continuity input for later temporal-spatial object tracking",
        ],
        cannot_prove=[
            "cannot prove one object persists by itself",
            "cannot distinguish sustained instrument from sustained mix texture alone",
        ],
        source_features=["rms.mean", "rms_delta.std"],
    )


def pulse_transfer_candidate(rhythm: dict[str, Any]) -> dict[str, Any]:
    onset_mean = stat_mean(rhythm, "onset_strength")
    beat_count = as_float(rhythm.get("beat_count"))
    score = bounded_score(relative_value(onset_mean, low=0.1, high=5.0), relative_value(beat_count, low=1.0, high=24.0))
    return candidate(
        field="pulse_transfer_candidate",
        layer="M-domain",
        value=score,
        confidence=confidence_from_values(onset_mean, beat_count),
        can_support=[
            "pulse or repeated-impact transfer candidate",
            "rhythmic event evidence for object candidate building",
        ],
        cannot_prove=[
            "cannot prove meter truth",
            "cannot prove groove quality",
            "cannot prove drum identity",
        ],
        source_features=["onset_strength.mean", "beat_count"],
    )


def perceived_pressure_candidate(temporal: dict[str, Any]) -> dict[str, Any]:
    rms_mean = stat_mean(temporal, "rms")
    rms_q75 = stat_value(temporal, "rms", "q75")
    score = bounded_score(relative_value(rms_mean, low=0.01, high=0.25), relative_value(rms_q75, low=0.015, high=0.35))
    return candidate(
        field="receiver_side_perceived_pressure_candidate",
        layer="E-space",
        value=score,
        confidence=confidence_from_values(rms_mean, rms_q75),
        can_support=[
            "receiver-side pressure candidate",
            "possible foreground weight evidence after calibration",
        ],
        cannot_prove=[
            "cannot prove near-field distance",
            "cannot prove emotional intensity",
        ],
        source_features=["rms.mean", "rms.q75"],
    )


def receiver_width_candidate(stereo: dict[str, Any]) -> dict[str, Any]:
    side_mid = as_float(stereo.get("side_to_mid_ratio"))
    score = relative_value(side_mid, low=0.05, high=1.2)
    return candidate(
        field="receiver_side_width_candidate",
        layer="E-space",
        value=score,
        confidence=confidence_from_values(side_mid) if stereo.get("available") else 0.0,
        can_support=[
            "stereo width or side-layer candidate",
            "receiver-side spread evidence",
        ],
        cannot_prove=[
            "cannot prove real physical source width",
            "cannot prove room size",
            "cannot prove surround field from stereo alone",
        ],
        source_features=["side_to_mid_ratio"],
    )


def receiver_balance_candidate(stereo: dict[str, Any]) -> dict[str, Any]:
    balance = as_float(stereo.get("lr_balance_negative_left_positive_right"))
    value = None if balance is None else round(balance, 8)
    return candidate(
        field="receiver_side_lr_balance_candidate",
        layer="E-space",
        value=value,
        confidence=confidence_from_values(balance) if stereo.get("available") else 0.0,
        can_support=[
            "left-right receiver balance candidate",
            "input for later spatial continuity across windows",
        ],
        cannot_prove=[
            "cannot prove object is physically left or right in real space",
            "cannot prove listener head position or speaker placement",
        ],
        source_features=["lr_balance_negative_left_positive_right"],
    )


def receiver_spread_candidate(stereo: dict[str, Any]) -> dict[str, Any]:
    corr = as_float(stereo.get("phase_correlation_proxy"))
    side_mid = as_float(stereo.get("side_to_mid_ratio"))
    decorrelation = None if corr is None else 1.0 - ((corr + 1.0) / 2.0)
    score = bounded_score(decorrelation, relative_value(side_mid, low=0.05, high=1.2))
    return candidate(
        field="receiver_side_spread_candidate",
        layer="E-space",
        value=score,
        confidence=confidence_from_values(corr, side_mid) if stereo.get("available") else 0.0,
        can_support=[
            "receiver-side diffusion or spread candidate",
            "possible non-centered layer evidence",
        ],
        cannot_prove=[
            "cannot prove reverb source or room geometry",
            "cannot prove physical envelopment without further evidence",
        ],
        source_features=["phase_correlation_proxy", "side_to_mid_ratio"],
    )


def upper_tendency_candidate(spectral: dict[str, Any]) -> dict[str, Any]:
    centroid = stat_mean(spectral, "spectral_centroid_hz")
    score = relative_value(centroid, low=800.0, high=5000.0)
    return candidate(
        field="receiver_side_upper_tendency_candidate",
        layer="E-space",
        value=score,
        confidence=confidence_from_values(centroid),
        can_support=[
            "receiver-side brightness or upper-register tendency candidate",
            "support for vertical / upper-layer report language only after calibration",
        ],
        cannot_prove=[
            "cannot prove a visual vertical position",
            "cannot directly become high, cold, glittering, or sharp report wording",
        ],
        source_features=["spectral_centroid_hz.mean"],
    )


def rhythmic_object_input(rhythm: dict[str, Any]) -> dict[str, Any]:
    onset_mean = stat_mean(rhythm, "onset_strength")
    beat_count = as_float(rhythm.get("beat_count"))
    score = bounded_score(relative_value(onset_mean, low=0.1, high=5.0), relative_value(beat_count, low=1.0, high=24.0))
    return candidate(
        field="rhythmic_object_input",
        layer="object-candidate-input",
        value=score,
        confidence=confidence_from_values(onset_mean, beat_count),
        can_support=[
            "possible repeated impact or pulse object candidate",
            "input for tracking object recurrence",
        ],
        cannot_prove=[
            "cannot prove kick, snare, drum, or percussion identity",
            "cannot prove groove quality or performance quality",
        ],
        source_features=["onset_strength.mean", "beat_count"],
    )


def transient_activity_input(rhythm: dict[str, Any], temporal: dict[str, Any]) -> dict[str, Any]:
    onset_max = stat_value(rhythm, "onset_strength", "max")
    rms_delta_max = stat_value(temporal, "rms_delta", "max")
    score = bounded_score(relative_value(onset_max, low=0.5, high=10.0), relative_value(rms_delta_max, low=0.01, high=0.25))
    return candidate(
        field="transient_activity_input",
        layer="object-candidate-input",
        value=score,
        confidence=confidence_from_values(onset_max, rms_delta_max),
        can_support=[
            "sudden event candidate",
            "attack or interruption evidence for later object segmentation",
        ],
        cannot_prove=[
            "cannot prove which source caused the transient",
            "cannot prove object boundary without continuity checks",
        ],
        source_features=["onset_strength.max", "rms_delta.max"],
    )


def harmonic_layer_input(harmonic: dict[str, Any]) -> dict[str, Any]:
    strength = as_float(harmonic.get("dominant_pitch_class_strength"))
    return candidate(
        field="harmonic_layer_input",
        layer="object-candidate-input",
        value=bounded_score(strength),
        confidence=confidence_from_values(strength),
        can_support=[
            "possible harmonic layer candidate",
            "input for recurring contour or tonal mass tracking",
        ],
        cannot_prove=[
            "cannot prove chord, key, melody, or instrument",
            "cannot prove voice-like object",
        ],
        source_features=["dominant_pitch_class_strength"],
    )


def texture_mass_input(spectral: dict[str, Any], mel_mfcc: dict[str, Any]) -> dict[str, Any]:
    flatness = stat_mean(spectral, "spectral_flatness")
    bandwidth = stat_mean(spectral, "spectral_bandwidth_hz")
    mfcc0 = list_stat_mean(mel_mfcc.get("mfcc_stats", []), 0)
    score = bounded_score(relative_value(flatness, low=0.02, high=0.45), relative_value(bandwidth, low=500.0, high=6000.0), relative_value(abs_or_none(mfcc0), low=10.0, high=300.0))
    return candidate(
        field="texture_mass_input",
        layer="object-candidate-input",
        value=score,
        confidence=confidence_from_values(flatness, bandwidth, mfcc0),
        can_support=[
            "possible broad texture or mass candidate",
            "input for fog/layer/noise-like object tracking only after later validation",
        ],
        cannot_prove=[
            "cannot prove noise wall, pad, guitar, synth, crowd, or vocal texture identity",
            "cannot become report metaphor without human calibration",
        ],
        source_features=["spectral_flatness.mean", "spectral_bandwidth_hz.mean", "mfcc_stats[0].mean"],
    )


def mapping_rule_index() -> list[dict[str, Any]]:
    return [
        {
            "rule": "RMS / RMS delta -> pressure and continuity candidates",
            "OME_target_field": ["M-domain.pressure_transfer_candidate", "E-space.receiver_side_perceived_pressure_candidate"],
            "can_support": "energy activity and pressure-transfer evidence",
            "cannot_prove": "physical distance, emotional intensity, or final loudness perception",
        },
        {
            "rule": "spectral centroid / rolloff -> brightness and upper-tendency candidates",
            "OME_target_field": ["O-space.source_side_spectral_brightness_candidate", "E-space.receiver_side_upper_tendency_candidate"],
            "can_support": "upper-frequency tendency evidence",
            "cannot_prove": "instrument identity, mood, or visual height",
        },
        {
            "rule": "side-to-mid ratio / LR balance / phase correlation -> receiver-side spatial proxy candidates",
            "OME_target_field": ["E-space.receiver_side_width_candidate", "E-space.receiver_side_lr_balance_candidate", "E-space.receiver_side_spread_candidate"],
            "can_support": "receiver-side width, balance, and spread proxies",
            "cannot_prove": "real physical 3D location or room geometry",
        },
        {
            "rule": "onset strength / beat evidence -> pulse and rhythmic object inputs",
            "OME_target_field": ["M-domain.pulse_transfer_candidate", "object-candidate-input.rhythmic_object_input"],
            "can_support": "pulse, recurrence, and transient-event candidates",
            "cannot_prove": "meter truth, drum identity, or groove quality",
        },
        {
            "rule": "chroma / mel / MFCC statistics -> harmonic and timbre-shape candidates",
            "OME_target_field": ["O-space.source_side_harmonic_contour_candidate", "object-candidate-input.harmonic_layer_input", "object-candidate-input.texture_mass_input"],
            "can_support": "coarse harmonic and texture-shape evidence",
            "cannot_prove": "key, melody, instrument, singer, speaker, or emotion",
        },
    ]


def candidate(
    field: str,
    layer: str,
    value: float | None,
    confidence: float,
    can_support: list[str],
    cannot_prove: list[str],
    source_features: list[str],
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    payload = {
        "field": field,
        "layer": layer,
        "value": safe_float(value),
        "confidence": safe_float(confidence),
        "source_features": source_features,
        "can_support": can_support,
        "cannot_prove": cannot_prove,
    }
    if extra:
        payload.update(extra)
    return payload


def stat_mean(container: dict[str, Any], key: str) -> float | None:
    return stat_value(container, key, "mean")


def stat_value(container: dict[str, Any], key: str, stat_key: str) -> float | None:
    item = container.get(key)
    if not isinstance(item, dict):
        return None
    return as_float(item.get(stat_key))


def list_stat_mean(items: Any, index: int) -> float | None:
    if not isinstance(items, list) or index >= len(items):
        return None
    item = items[index]
    if not isinstance(item, dict):
        return None
    return as_float(item.get("mean"))


def abs_or_none(value: float | None) -> float | None:
    return None if value is None else abs(value)


def relative_value(value: float | None, low: float, high: float) -> float | None:
    if value is None:
        return None
    if high <= low:
        return None
    return clamp01((value - low) / (high - low))


def bounded_score(*values: float | None) -> float | None:
    valid = [value for value in values if value is not None and math.isfinite(value)]
    if not valid:
        return None
    return clamp01(sum(valid) / len(valid))


def confidence_from_values(*values: Any) -> float:
    if not values:
        return 0.0
    valid_count = sum(1 for value in values if as_float(value) is not None)
    return clamp01(valid_count / len(values))


def clamp01(value: float | None) -> float | None:
    if value is None or not math.isfinite(value):
        return None
    return max(0.0, min(1.0, float(value)))


def as_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(result):
        return None
    return result


def safe_float(value: Any) -> float | None:
    result = as_float(value)
    if result is None:
        return None
    return round(result, 8)


def sanitize(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): sanitize(item) for key, item in value.items()}
    if isinstance(value, list):
        return [sanitize(item) for item in value]
    if isinstance(value, tuple):
        return [sanitize(item) for item in value]
    if isinstance(value, float):
        return safe_float(value)
    return value


if __name__ == "__main__":
    main()
